---

- hosts: localhost
  connection: local
  tasks:
    - name: show library
      command: chflags nohidden {{ home_dir }}/Library
      tags: stat

  roles:
    - brew
    - defaults
    - go
    - highlight
    - me
    - nodejs
    - python
    - ruby
    - ssh
    - workspace
