---
- hosts: all
  connection: local

  pre_tasks:
  - include_vars: "{{ item }}"
    with_fileglob:
    - "{{ playbook_dir }}/conf/*.yml"
    tags:
    - always

  roles:
  - elliotweiser.osx-command-line-tools
  - homebrew
  - mas

  - ruby
  - shells
