---
- name: install homebrew-cask
  command: brew install caskroom/cask/brew-cask
  args:
    creates: /usr/local/bin/brew-cask

- name: brew taps
  homebrew_tap:
    tap: "{{ item }}"
  with_items: brew_taps

- name: brew packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
  notify: brew linkapps
  with_items: brew_packages

- name: cask applications
  homebrew_cask: name={{ item }}
  with_items: cask_applications
