---
- name: include secret vars
  include_vars: "group_vars/secret.yml"
  tags: network

- name: set dns servers
  command: "sudo networksetup -setdnsservers '{{ item }}' {{ dns_servers|join(' ') }}"
  with_items: "{{ dns_interfaces }}"
  tags: network
