---
- name: gocode
  file: path={{ home_dir }}/gocode state=directory
  tags: go

- name: go get packages
  command: go get {{ item }}
  with_items: "{{ go_packages }}"
  ignore_errors: yes
  tags: go

# https://gist.github.com/bryanl/465a188d8495a2457fa8
- name: godoc launchctl config
  template:
    src: godoc.plist
    dest: "{{ home_dir }}/Library/LaunchAgents/rcolvin.godoc.plist"
  tags: go

- name: godoc launchctl load
  command: "launchctl load {{ home_dir }}/Library/LaunchAgents/rcolvin.godoc.plist"
  tags: go
